apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-sample
    app.kubernetes.io/part-of: test-samples
  name: java-quarkus-sample
  namespace: mdsaud
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-sample
status:
  loadBalancer: {}
