apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-sample
    app.kubernetes.io/part-of: test-samples
  name: nodejs-sample
  namespace: mdsaud
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejs-sample
status:
  loadBalancer: {}
